### ISSUE TITLE
Trend task

### ISSUE THREAD

**Issue by MC-Team2212** [KaustubhPatange/YTPlayer#10] opened 2020-05-02 00:11 UTC
Trend Task isn't working

**Comment by KaustubhPatange** [comment] 2020-05-02 11:25
https://drive.google.com/file/d/1U_lMlCOHBxdciiVTsf2kZn3EKu566e08/view

Use this version it has been fixed!

**Comment by KaustubhPatange** [comment] 2020-05-02 11:26
There seems to be an issue with spotify library. I will fix it soon

**Comment by MC-Team2212** [comment] 2020-05-02 11:26
I wondered where the error is and the solution if it won't be a problem
you bildirirmis

**Comment by MC-Team2212** [comment] 2020-05-02 11:27
I am working on you, you are the creator but I will let you know if I solve it

**Comment by KaustubhPatange** [comment] 2020-05-02 11:27
It seems problem with spotify api which is causing the problem. Let me quickly look into that problem

**Comment by MC-Team2212** [comment] 2020-05-02 11:29
I made some logging and I think the source is here.


05-02 19:22:50.482 18621-18793/com.mc.onmusic_relase E/TrendingLines: Blueberry Faygo
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.util.ArrayList.get(ArrayList.java:308)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at com.mc.onmusic_relase.fragments.SearchFragment$getTrending.doInBackground(SearchFragment.java:819)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at com.mc.onmusic_relase.fragments.SearchFragment$getTrending.doInBackground(SearchFragment.java:736)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-02 19:22:51.197 18621-18793/com.mc.onmusic_relase W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by KaustubhPatange** [comment] 2020-05-02 11:39
Problem lies in YTSearch.java file. It is not returning list of video ids

**Comment by MC-Team2212** [comment] 2020-05-02 11:40
Yes, there was a crash when I searched with the spotify link

**Comment by MC-Team2212** [comment] 2020-05-02 11:41
I also love you very much

**Comment by KaustubhPatange** [comment] 2020-05-02 12:52
The issue is fixed in the latest release!

**Closed by KaustubhPatange** 2020-05-02 12:52 UTC

**Comment by MC-Team2212** [comment] 2020-05-02 16:41
Thank you
